development:
  :chemspectra:
    :url: 'http://127.0.0.1:3007'
  :nmriumwrapper:
    :url: 'https://nmrium.nmrxiv.org'

test:
  :chemspectra:
    :url: 'http://127.0.0.1:3007'
  :nmriumwrapper:
    :url: 'https://nmrium.nmrxiv.org'

production:
  :chemspectra:
    :url: 'http://127.0.0.1:3007'
  :nmriumwrapper:
    :url: 'https://nmrium.nmrxiv.org'
